server:
  port: 12001

spring:
  datasource:
    username: 'root'
    password: '123456'
    url: jdbc:mysql://localhost:13306/gulimall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
