server:
  port: 11000

spring:
  application:
    name: gulimall-product
  cloud:
    nacos:
      discovery:
        server-addr: 116.198.200.0:8848
  datasource:
    username: 'root'
    password: '123456'
    url: jdbc:mysql://116.198.200.0:3306/gulimall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 116.198.200.0
    port: 6379
    password: 123456

  cache:
    type: redis
    redis:
      time-to-live: 3600000
      use-key-prefix: true

  #关闭thymeleaf缓存
  thymeleaf:
    cache: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
