server:
  port: 11000

spring:
  application:
    name: gulimall-product
  cloud:
    nacos:
      discovery:
        server-addr: 114.55.150.242:8848
  datasource:
    username: 'root'
    password: '123456'
    url: jdbc:mysql://114.55.150.242:3306/gulimall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
