server:
  port: 12000

spring:
  application:
    name: gulimall-coupon
  cloud:
    nacos:
      discovery:
        server-addr: 114.55.150.242:8848
  datasource:
    username: 'root'
    password: '123456'
    url: jdbc:mysql://114.55.150.242:3306/gulimall_sms
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
