server:
  port: 14000

spring:
  datasource:
    username: 'root'
    password: '123456'
    url: jdbc:mysql://localhost:13306/gulimall_oms
    driver-class-name: com.mysql.cj.jdbc.Driver

  rabbitmq:
    host:
    port: 5672
    publisher-confirms: true
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual

  thymeleaf:
    cache: false

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
