server:
  port: 14000

spring:
  datasource:
    username: 'root'
    password: '123456'
    url: jdbc:mysql://localhost:13306/gulimall_oms
    driver-class-name: com.mysql.cj.jdbc.Driver

  rabbitmq:
    host:
    port: 5672
    publisher-confirms: true
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual

  redis:
    host: 116.198.200.0
    port: 6379
    password: 123456

  thymeleaf:
    cache: false

mybatis-plus:
  global-config:
    db-config:
      id-type: auto

gulimall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10