server:
  port: 17000

spring:
  application:
    name: gulimall-search
  cloud:
    nacos:
      discovery:
        server-addr: 116.198.200.0:8848
#  datasource:
#    username: 'root'
#    password: '123456'
#    url: jdbc:mysql://116.198.200.0:3306/gulimall_pms
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

gulimall:
  es:
    config:
      hostname: '114.55.150.242'
      port: 9200
      scheme: 'http'