server:
  port: 15000

spring:
  application:
    name: gulimall-ware
  cloud:
    nacos:
      discovery:
        server-addr: 116.198.200.0:8848
  datasource:
    username: 'root'
    password: '123456'
    url: jdbc:mysql://116.198.200.0:3306/gulimall_wms
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
